### ISSUE TITLE
SidebarModule does not scroll on touch devices

### ISSUE THREAD

**Issue by Gskartwii** [CrescentCode/ValkyrieFramework#1]

**Comment by eLunate** [comment]
Anything more on this?

**Comment by Gskartwii** [comment]
Not yet. I thought the input module was supposed to resolve this somehow.

**Comment by eLunate** [comment]
Well, I think the main issue was that no schema was decided/adopted for how the scrolling was to be done. I can implement something like `ValkyrieInput:AttachScrolling(ScrollingFrame ScrollSource) -> connection SignalController` but it's all down to whether the thing is expected to use a ScrollingFrame or a Frame.

**Comment by Gskartwii** [comment]
I can totally make it a ScrollingFrame, it will make stuff much easier for everybody.

I originally though of not using ScrollingFrames because I thought they would only get in the way by being choppy at scrolling, but you can obviously override that.

**Comment by TickerOfTime** [comment]
Hey hey. You can use my smooth scrolling technique if you would like.

**Comment by jeffy123459** [comment]
hi hi i am a random scrub and i dislike roblox's poopy scrollbar. Can I use your's ticker of time?
