### ISSUE TITLE
Time.mod.lua functions incorrectly

### ISSUE THREAD

**Issue by Gskartwii** [CrescentCode/ValkyrieFramework#38]
Originally reported by Roblox user Narrev:

> As far as I can tell, the Valkyrie time Module is not functioning properly. The issue is in the way the tables are assembled. Regardless, I wrote a module that adds os.date back to the os table. It is very well tested, fully functional, and fully optimized as far as I can tell.
> 
> Google Nevermore Engine. It's on Github, created by Quenty. Once there, navigate to NevermoreEngine/Modules/Utility/os

> That's NevermoreEngine.Modules.Utility.os

> Alternatively, check me out on Github. I posted some Unix-Epoch-Date-and-Time-Calculations. Via annotations, I labelled which one is the most efficient method of getting the date and time (third function). It's called GetYMDFromSeconds. Good luck

**Comment by eLunate** [comment]
"It's broken, fix your shit."
If he ever says what is wrong, I'll fix it. Otherwise I'm not going blindly looking for 'some issue with the tables'
