### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by ToastEngine** [CrescentCode/ValkyrieFramework#44]
Can't signup, I set the message settings correctly. Then send the message to the bot, hit verify the green loading circle just keeps spinning please help.

**Comment by eLunate** [comment]
I'd advise that for the moment you wait before you try to sign up for Valkyrie because the interfaces are being redesigned to be more universal.

**Comment by Gskartwii** [comment]
I've moved this issue to CrescentCode/ValkyrieServer#11
