### ISSUE TITLE
Still can't create account.

### ISSUE THREAD

**Issue by ToastEngine** [CrescentCode/ValkyrieFramework#45]
Its been about a month, Still can't create and account. I followed the directions. I tried on multiple browsers too. Please fix.

**Comment by eLunate** [comment]
It has been a month, but due to slow progress you are still advised to either

* Give instructions to reproduce the issue
* Wait for the Valkyrie stable release.

**Comment by ToastEngine** [comment]
Steps:
1. Go too Signup page of ValkyrieFramework.
2. Input username
3. Create password
4. Hit signup.
5. Follow ValkyrieBot on roblox and change message settings to allow messages from followers and friends
6. Message ValkyrieBot with subject [Random Key] and Body [Random Key].
7. Hit verify

Outcome:
Green circle just spins never stopping.

Chrome console outputs:
Failed to load resource: the server responded with a status of 500 ()  https://valkyrie.crescentcode.net/signup/2

How will I know when the stable release is done?

**Comment by eLunate** [comment]
If you're on the Forums, I'll be sure to get announcements out. Otherwise, provided Valkyrie is all that it should promise to be, you'll hear very quickly when it is stable so long as you're following it.

**Comment by Gskartwii** [comment]
Sorry for the inconvenience, I was busy and forgot about this issue. It appears to be fixed now.

**Comment by ToastEngine** [comment]
You fixed it thanks!
