### ISSUE TITLE
Better Sidebar scrolling system

### ISSUE THREAD

**Issue by Gskartwii** [CrescentCode/ValkyrieFramework#9]
Currently the Sidebar uses an explicit and hacky system for reacting to mouse scrolling events. Ideally I'd like to have a generalized and simple component for scrolling.

**Comment by eLunate** [comment]
Should we make a Component that can attach to a Frame (Or ScrollingFrame, for native reasons) and bind all description of events to it?

**Comment by Gskartwii** [comment]
That's what I had in mind. I'm probably going to support both Frames and ScrollingFrames but going to translate them to ScrollingFrames.

**Comment by eLunate** [comment]
I might take a look at it. How would it look? Would we convert Frames to ScrollingFrames to maintain native support, or would we convert ScrollingFrames to Frames and bind all input events for aesthetics reasons? If we get that out of the way I could take a look at helping to engineer a solution for it.

**Comment by Gskartwii** [comment]
In fact I think the best solution is to use ScrollingFrames AND bind input events to them so that the content doesn't overlap when it's scrolled up.

**Comment by eLunate** [comment]
On this note...
Should we perhaps look at making a unified input capturing system to extend UIS/CAS/GUI input, with extra hooks and things? If we do, I can look at migrating a lot of the input-based things to it after it is sorted out.

**Comment by Gskartwii** [comment]
Definitely. It's always a good habit to make generalized code.

**Comment by eLunate** [comment]
How should it work? What would we bind to or provide, and where/how?

**Comment by Gskartwii** [comment]
At least scrolling support for any Frames that works better than ScrollingFrames and supports both PC and touch (#9)
Maybe a few variations of input cues (#2, [The `input-cues` branch](https://github.com/ValkyrieRBXL/ValkyrieFramework/tree/input-cues))
And probably a touch input system that is easier to use than UIS.

That's all I can think of right this second, but I'm sure that a lot more will be required.

**Comment by eLunate** [comment]
I'll see if I can grab all the input APIs and see what I can come up with.
